### PR TITLE
Add new provider: SMSBOX.COM

### PR DESCRIPTION
**Pull request by adnanebrahimi**
Add new provider for Kuwaitis number: SMSBOX.COM

### CODE REVIEW

**Comment by artprojectgroup** [comment]
We'll add it as soon as possible.

Kind regards.

**Comment by artprojectgroup** [comment]
Sorry we don't understand why did you add this: str_replace('','+',$telefono) in recipientNumbers, 'false' in isBlink and isFlash, and ' ' in defDate.

Where's published the full API documentation? Because in https://www.smsbox.com/API/SendShortMessage#class-desc we can't see how to send that fields.

Kind regards.

**Comment by adnanebrahimi** [comment]
Hello,

- The recipientNumber is Message recipient numbers comma(,) separated
- the defDate is Message sechedule date (allow null)
- isFlash means Flash SMS that is not usable 
- isBlink means Blink SMS that is not usable

The API needs these parameters to be set.

Read More:
http://smsbox.com/API/SendShortMessage

**Comment by artprojectgroup** [comment]
Sorry but we can't add this provider to our plugin if we're not sure that your code has no issues, and we can't know that because the API documentation is too poor and doesn't provide enough information.

Kind regards.

**Comment by adnanebrahimi** [comment]
I understand your concern.

How can I make you sure about this Provider? Do you need any official request from them?

**Comment by artprojectgroup** [comment]
No, we need the full code without issues.

Kind regards.

**Pull request closed without merging**
